### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/ajdamico/usgsd | https://github.com/ajdamico/asdfree |
| https://github.com/armstrtw/Rblpapi | https://github.com/Rblp/Rblpapi |
| https://github.com/fmichonneau/rotl | https://github.com/ropensci/rotl |
| https://github.com/hadley/bigrquery | https://github.com/rstats-db/bigrquery |
| https://github.com/leeper/Rmonkey/ | https://github.com/cloudyr/Rmonkey |
| https://github.com/lmullen/internetarchive | https://github.com/ropensci/internetarchive |
| https://github.com/ropensci/opendata/wiki/ToDo | https://github.com/ropensci/webservices/wiki/ToDo |
| https://github.com/ropensci/spoccutils | https://github.com/ropensci/mapr |
### HTTPS Corrected URLs

| Was | Now |
| --- | --- |
| http://cran.rstudio.com/src/contrib/Archive/BerkeleyEarth/ | https://cran.rstudio.com/src/contrib/Archive/BerkeleyEarth/ |
| http://cran.rstudio.com/src/contrib/Archive/Metadata/ | https://cran.rstudio.com/src/contrib/Archive/Metadata/ |
| http://cran.rstudio.com/src/contrib/Archive/NCBI2R/ | https://cran.rstudio.com/src/contrib/Archive/NCBI2R/ |
| http://cran.rstudio.com/src/contrib/Archive/RMendeley/ | https://cran.rstudio.com/src/contrib/Archive/RMendeley/ |
| http://cran.rstudio.com/src/contrib/Archive/RSocrata/ | https://cran.rstudio.com/src/contrib/Archive/RSocrata/ |
| http://cran.rstudio.com/src/contrib/Archive/cimis/ | https://cran.rstudio.com/src/contrib/Archive/cimis/ |
| http://cran.rstudio.com/src/contrib/Archive/dataone/ | https://cran.rstudio.com/src/contrib/Archive/dataone/ |
| http://cran.rstudio.com/src/contrib/Archive/googlePublicData/ | https://cran.rstudio.com/src/contrib/Archive/googlePublicData/ |
| http://cran.rstudio.com/src/contrib/Archive/infochimps/ | https://cran.rstudio.com/src/contrib/Archive/infochimps/ |
| http://cran.rstudio.com/src/contrib/Archive/seq2R/ | https://cran.rstudio.com/src/contrib/Archive/seq2R/ |
| http://cran.rstudio.com/src/contrib/Archive/wethepeople/ | https://cran.rstudio.com/src/contrib/Archive/wethepeople/ |
| http://cran.rstudio.com/web/packages/BerlinData/index.html | https://cran.rstudio.com/web/packages/BerlinData/index.html |
| http://cran.rstudio.com/web/packages/CHCN/index.html | https://cran.rstudio.com/web/packages/CHCN/index.html |
| http://cran.rstudio.com/web/packages/EIAdata/index.html | https://cran.rstudio.com/web/packages/EIAdata/index.html |
| http://cran.rstudio.com/web/packages/FAOSTAT/index.html | https://cran.rstudio.com/web/packages/FAOSTAT/index.html |
| http://cran.rstudio.com/web/packages/FedData/index.html | https://cran.rstudio.com/web/packages/FedData/index.html |
| http://cran.rstudio.com/web/packages/GAR/index.html | https://cran.rstudio.com/web/packages/GAR/index.html |
| http://cran.rstudio.com/web/packages/GuardianR/index.html | https://cran.rstudio.com/web/packages/GuardianR/index.html |
| http://cran.rstudio.com/web/packages/IBrokers/index.html | https://cran.rstudio.com/web/packages/IBrokers/index.html |
| http://cran.rstudio.com/web/packages/MBTAr/index.html | https://cran.rstudio.com/web/packages/MBTAr/index.html |
| http://cran.rstudio.com/web/packages/OAIHarvester/index.html | https://cran.rstudio.com/web/packages/OAIHarvester/index.html |
| http://cran.rstudio.com/web/packages/OECD/index.html | https://cran.rstudio.com/web/packages/OECD/index.html |
| http://cran.rstudio.com/web/packages/ONETr/index.html | https://cran.rstudio.com/web/packages/ONETr/index.html |
| http://cran.rstudio.com/web/packages/Quandl/index.html | https://cran.rstudio.com/web/packages/Quandl/index.html |
| http://cran.rstudio.com/web/packages/RAdwords/index.html | https://cran.rstudio.com/web/packages/RAdwords/index.html |
| http://cran.rstudio.com/web/packages/RCryptsy/index.html | https://cran.rstudio.com/web/packages/RCryptsy/index.html |
| http://cran.rstudio.com/web/packages/RForcecom/index.html | https://cran.rstudio.com/web/packages/RForcecom/index.html |
| http://cran.rstudio.com/web/packages/RGA/index.html | https://cran.rstudio.com/web/packages/RGA/index.html |
| http://cran.rstudio.com/web/packages/RGoogleAnalytics/index.html | https://cran.rstudio.com/web/packages/RGoogleAnalytics/index.html |
| http://cran.rstudio.com/web/packages/RISmed/index.html | https://cran.rstudio.com/web/packages/RISmed/index.html |
| http://cran.rstudio.com/web/packages/RJSDMX/index.html | https://cran.rstudio.com/web/packages/RJSDMX/index.html |
| http://cran.rstudio.com/web/packages/RKlout/index.html | https://cran.rstudio.com/web/packages/RKlout/index.html |
| http://cran.rstudio.com/web/packages/RNCEP/index.html | https://cran.rstudio.com/web/packages/RNCEP/index.html |
| http://cran.rstudio.com/web/packages/RPublica/index.html | https://cran.rstudio.com/web/packages/RPublica/index.html |
| http://cran.rstudio.com/web/packages/RSiteCatalyst/index.html | https://cran.rstudio.com/web/packages/RSiteCatalyst/index.html |
| http://cran.rstudio.com/web/packages/RStars/index.html | https://cran.rstudio.com/web/packages/RStars/index.html |
| http://cran.rstudio.com/web/packages/Rbitcoin/index.html | https://cran.rstudio.com/web/packages/Rbitcoin/index.html |
| http://cran.rstudio.com/web/packages/Rcolombos/index.html | https://cran.rstudio.com/web/packages/Rcolombos/index.html |
| http://cran.rstudio.com/web/packages/RedditExtractoR/index.html | https://cran.rstudio.com/web/packages/RedditExtractoR/index.html |
| http://cran.rstudio.com/web/packages/RefManageR/index.html | https://cran.rstudio.com/web/packages/RefManageR/index.html |
| http://cran.rstudio.com/web/packages/Reol/index.html | https://cran.rstudio.com/web/packages/Reol/index.html |
| http://cran.rstudio.com/web/packages/Rfacebook/index.html | https://cran.rstudio.com/web/packages/Rfacebook/index.html |
| http://cran.rstudio.com/web/packages/RgoogleMaps/index.html | https://cran.rstudio.com/web/packages/RgoogleMaps/index.html |
| http://cran.rstudio.com/web/packages/Rlinkedin/index.html | https://cran.rstudio.com/web/packages/Rlinkedin/index.html |
| http://cran.rstudio.com/web/packages/SocialMediaLab/index.html | https://cran.rstudio.com/web/packages/SocialMediaLab/index.html |
| http://cran.rstudio.com/web/packages/SocialMediaMineR/index.html | https://cran.rstudio.com/web/packages/SocialMediaMineR/index.html |
| http://cran.rstudio.com/web/packages/SoyNAM/index.html | https://cran.rstudio.com/web/packages/SoyNAM/index.html |
| http://cran.rstudio.com/web/packages/TFX/index.html | https://cran.rstudio.com/web/packages/TFX/index.html |
| http://cran.rstudio.com/web/packages/TMDb/index.html | https://cran.rstudio.com/web/packages/TMDb/index.html |
| http://cran.rstudio.com/web/packages/TR8/index.html | https://cran.rstudio.com/web/packages/TR8/index.html |
| http://cran.rstudio.com/web/packages/Thinknum/index.html | https://cran.rstudio.com/web/packages/Thinknum/index.html |
| http://cran.rstudio.com/web/packages/UNF/index.html | https://cran.rstudio.com/web/packages/UNF/index.html |
| http://cran.rstudio.com/web/packages/USAboundaries/index.html | https://cran.rstudio.com/web/packages/USAboundaries/index.html |
| http://cran.rstudio.com/web/packages/UScancer/index.html | https://cran.rstudio.com/web/packages/UScancer/index.html |
| http://cran.rstudio.com/web/packages/WDI/index.html | https://cran.rstudio.com/web/packages/WDI/index.html |
| http://cran.rstudio.com/web/packages/WHO/index.html | https://cran.rstudio.com/web/packages/WHO/index.html |
| http://cran.rstudio.com/web/packages/WaterML/index.html | https://cran.rstudio.com/web/packages/WaterML/index.html |
| http://cran.rstudio.com/web/packages/WikidataR/index.html | https://cran.rstudio.com/web/packages/WikidataR/index.html |
| http://cran.rstudio.com/web/packages/WikipediR/index.html | https://cran.rstudio.com/web/packages/WikipediR/index.html |
| http://cran.rstudio.com/web/packages/aRxiv/index.html | https://cran.rstudio.com/web/packages/aRxiv/index.html |
| http://cran.rstudio.com/web/packages/acs/index.html | https://cran.rstudio.com/web/packages/acs/index.html |
| http://cran.rstudio.com/web/packages/alm/index.html | https://cran.rstudio.com/web/packages/alm/index.html |
| http://cran.rstudio.com/web/packages/ameco/index.html | https://cran.rstudio.com/web/packages/ameco/index.html |
| http://cran.rstudio.com/web/packages/bigrquery/index.html | https://cran.rstudio.com/web/packages/bigrquery/index.html |
| http://cran.rstudio.com/web/packages/biorxivr/index.html | https://cran.rstudio.com/web/packages/biorxivr/index.html |
| http://cran.rstudio.com/web/packages/blsAPI/index.html | https://cran.rstudio.com/web/packages/blsAPI/index.html |
| http://cran.rstudio.com/web/packages/boilerpipeR/index.html | https://cran.rstudio.com/web/packages/boilerpipeR/index.html |
| http://cran.rstudio.com/web/packages/brewdata/index.html | https://cran.rstudio.com/web/packages/brewdata/index.html |
| http://cran.rstudio.com/web/packages/cbsodataR/index.html | https://cran.rstudio.com/web/packages/cbsodataR/index.html |
| http://cran.rstudio.com/web/packages/censusr/index.html | https://cran.rstudio.com/web/packages/censusr/index.html |
| http://cran.rstudio.com/web/packages/cgdsr/index.html | https://cran.rstudio.com/web/packages/cgdsr/index.html |
| http://cran.rstudio.com/web/packages/chromer/index.html | https://cran.rstudio.com/web/packages/chromer/index.html |
| http://cran.rstudio.com/web/packages/clifro/index.html | https://cran.rstudio.com/web/packages/clifro/index.html |
| http://cran.rstudio.com/web/packages/crandatapkgs/index.html | https://cran.rstudio.com/web/packages/crandatapkgs/index.html |
| http://cran.rstudio.com/web/packages/cricketr/index.html | https://cran.rstudio.com/web/packages/cricketr/index.html |
| http://cran.rstudio.com/web/packages/crn/index.html | https://cran.rstudio.com/web/packages/crn/index.html |
| http://cran.rstudio.com/web/packages/dataRetrieval/index.html | https://cran.rstudio.com/web/packages/dataRetrieval/index.html |
| http://cran.rstudio.com/web/packages/datamart/index.html | https://cran.rstudio.com/web/packages/datamart/index.html |
| http://cran.rstudio.com/web/packages/dataonderivatives/index.html | https://cran.rstudio.com/web/packages/dataonderivatives/index.html |
| http://cran.rstudio.com/web/packages/decctools/index.html | https://cran.rstudio.com/web/packages/decctools/index.html |
| http://cran.rstudio.com/web/packages/diezeit/index.html | https://cran.rstudio.com/web/packages/diezeit/index.html |
| http://cran.rstudio.com/web/packages/dismo/index.html | https://cran.rstudio.com/web/packages/dismo/index.html |
| http://cran.rstudio.com/web/packages/dvn/index.html | https://cran.rstudio.com/web/packages/dvn/index.html |
| http://cran.rstudio.com/web/packages/easyPubMed/index.html | https://cran.rstudio.com/web/packages/easyPubMed/index.html |
| http://cran.rstudio.com/web/packages/ecb/index.html | https://cran.rstudio.com/web/packages/ecb/index.html |
| http://cran.rstudio.com/web/packages/ecoengine/index.html | https://cran.rstudio.com/web/packages/ecoengine/index.html |
| http://cran.rstudio.com/web/packages/ecoretriever/index.html | https://cran.rstudio.com/web/packages/ecoretriever/index.html |
| http://cran.rstudio.com/web/packages/elexr/index.html | https://cran.rstudio.com/web/packages/elexr/index.html |
| http://cran.rstudio.com/web/packages/enigma/index.html | https://cran.rstudio.com/web/packages/enigma/index.html |
| http://cran.rstudio.com/web/packages/eurostat/index.html | https://cran.rstudio.com/web/packages/eurostat/index.html |
| http://cran.rstudio.com/web/packages/fImport/index.html | https://cran.rstudio.com/web/packages/fImport/index.html |
| http://cran.rstudio.com/web/packages/factualR/index.html | https://cran.rstudio.com/web/packages/factualR/index.html |
| http://cran.rstudio.com/web/packages/fbRanks/index.html | https://cran.rstudio.com/web/packages/fbRanks/index.html |
| http://cran.rstudio.com/web/packages/federalregister/index.html | https://cran.rstudio.com/web/packages/federalregister/index.html |
| http://cran.rstudio.com/web/packages/fitbitScraper/index.html | https://cran.rstudio.com/web/packages/fitbitScraper/index.html |
| http://cran.rstudio.com/web/packages/flora/index.html | https://cran.rstudio.com/web/packages/flora/index.html |
| http://cran.rstudio.com/web/packages/genderizeR/index.html | https://cran.rstudio.com/web/packages/genderizeR/index.html |
| http://cran.rstudio.com/web/packages/geocodeHERE/index.html | https://cran.rstudio.com/web/packages/geocodeHERE/index.html |
| http://cran.rstudio.com/web/packages/gesis/index.html | https://cran.rstudio.com/web/packages/gesis/index.html |
| http://cran.rstudio.com/web/packages/ggmap/index.html | https://cran.rstudio.com/web/packages/ggmap/index.html |
| http://cran.rstudio.com/web/packages/googleVis/index.html | https://cran.rstudio.com/web/packages/googleVis/index.html |
| http://cran.rstudio.com/web/packages/govStatJPN/index.html | https://cran.rstudio.com/web/packages/govStatJPN/index.html |
| http://cran.rstudio.com/web/packages/gsheet/index.html | https://cran.rstudio.com/web/packages/gsheet/index.html |
| http://cran.rstudio.com/web/packages/hddtools/index.html | https://cran.rstudio.com/web/packages/hddtools/index.html |
| http://cran.rstudio.com/web/packages/hdr/index.html | https://cran.rstudio.com/web/packages/hdr/index.html |
| http://cran.rstudio.com/web/packages/hoardeR/index.html | https://cran.rstudio.com/web/packages/hoardeR/index.html |
| http://cran.rstudio.com/web/packages/imguR/index.html | https://cran.rstudio.com/web/packages/imguR/index.html |
| http://cran.rstudio.com/web/packages/inegiR/index.html | https://cran.rstudio.com/web/packages/inegiR/index.html |
| http://cran.rstudio.com/web/packages/jSonarR/index.html | https://cran.rstudio.com/web/packages/jSonarR/index.html |
| http://cran.rstudio.com/web/packages/leafletR/index.html | https://cran.rstudio.com/web/packages/leafletR/index.html |
| http://cran.rstudio.com/web/packages/lumendb/index.html | https://cran.rstudio.com/web/packages/lumendb/index.html |
| http://cran.rstudio.com/web/packages/maddison/index.html | https://cran.rstudio.com/web/packages/maddison/index.html |
| http://cran.rstudio.com/web/packages/manifestoR/index.html | https://cran.rstudio.com/web/packages/manifestoR/index.html |
| http://cran.rstudio.com/web/packages/marmap/index.html | https://cran.rstudio.com/web/packages/marmap/index.html |
| http://cran.rstudio.com/web/packages/meteoForecast/index.html | https://cran.rstudio.com/web/packages/meteoForecast/index.html |
| http://cran.rstudio.com/web/packages/neotoma/index.html | https://cran.rstudio.com/web/packages/neotoma/index.html |
| http://cran.rstudio.com/web/packages/nhanesA/index.html | https://cran.rstudio.com/web/packages/nhanesA/index.html |
| http://cran.rstudio.com/web/packages/nhlscrapr/index.html | https://cran.rstudio.com/web/packages/nhlscrapr/index.html |
| http://cran.rstudio.com/web/packages/oai/index.html | https://cran.rstudio.com/web/packages/oai/index.html |
| http://cran.rstudio.com/web/packages/okmesonet/index.html | https://cran.rstudio.com/web/packages/okmesonet/index.html |
| http://cran.rstudio.com/web/packages/olctools/index.html | https://cran.rstudio.com/web/packages/olctools/index.html |
| http://cran.rstudio.com/web/packages/ores/index.html | https://cran.rstudio.com/web/packages/ores/index.html |
| http://cran.rstudio.com/web/packages/osmar/index.html | https://cran.rstudio.com/web/packages/osmar/index.html |
| http://cran.rstudio.com/web/packages/osrm/index.html | https://cran.rstudio.com/web/packages/osrm/index.html |
| http://cran.rstudio.com/web/packages/pageviews/index.html | https://cran.rstudio.com/web/packages/pageviews/index.html |
| http://cran.rstudio.com/web/packages/paleobioDB/index.html | https://cran.rstudio.com/web/packages/paleobioDB/index.html |
| http://cran.rstudio.com/web/packages/pdfetch/index.html | https://cran.rstudio.com/web/packages/pdfetch/index.html |
| http://cran.rstudio.com/web/packages/pinnacle.API/index.html | https://cran.rstudio.com/web/packages/pinnacle.API/index.html |
| http://cran.rstudio.com/web/packages/pitchRx/index.html | https://cran.rstudio.com/web/packages/pitchRx/index.html |
| http://cran.rstudio.com/web/packages/plotGoogleMaps/index.html | https://cran.rstudio.com/web/packages/plotGoogleMaps/index.html |
| http://cran.rstudio.com/web/packages/plotKML/index.html | https://cran.rstudio.com/web/packages/plotKML/index.html |
| http://cran.rstudio.com/web/packages/plusser/index.html | https://cran.rstudio.com/web/packages/plusser/index.html |
| http://cran.rstudio.com/web/packages/polidata/index.html | https://cran.rstudio.com/web/packages/polidata/index.html |
| http://cran.rstudio.com/web/packages/pollstR/index.html | https://cran.rstudio.com/web/packages/pollstR/index.html |
| http://cran.rstudio.com/web/packages/primerTree/index.html | https://cran.rstudio.com/web/packages/primerTree/index.html |
| http://cran.rstudio.com/web/packages/prism/index.html | https://cran.rstudio.com/web/packages/prism/index.html |
| http://cran.rstudio.com/web/packages/psidR/index.html | https://cran.rstudio.com/web/packages/psidR/index.html |
| http://cran.rstudio.com/web/packages/pubmed.mineR/index.html | https://cran.rstudio.com/web/packages/pubmed.mineR/index.html |
| http://cran.rstudio.com/web/packages/pvsR/index.html | https://cran.rstudio.com/web/packages/pvsR/index.html |
| http://cran.rstudio.com/web/packages/pxweb/index.html | https://cran.rstudio.com/web/packages/pxweb/index.html |
| http://cran.rstudio.com/web/packages/quantmod/index.html | https://cran.rstudio.com/web/packages/quantmod/index.html |
| http://cran.rstudio.com/web/packages/rAltmetric/index.html | https://cran.rstudio.com/web/packages/rAltmetric/index.html |
| http://cran.rstudio.com/web/packages/rClinicalCodes/index.html | https://cran.rstudio.com/web/packages/rClinicalCodes/index.html |
| http://cran.rstudio.com/web/packages/rFDSN/index.html | https://cran.rstudio.com/web/packages/rFDSN/index.html |
| http://cran.rstudio.com/web/packages/rNOMADS/index.html | https://cran.rstudio.com/web/packages/rNOMADS/index.html |
| http://cran.rstudio.com/web/packages/rPlant/index.html | https://cran.rstudio.com/web/packages/rPlant/index.html |
| http://cran.rstudio.com/web/packages/rWBclimate/index.html | https://cran.rstudio.com/web/packages/rWBclimate/index.html |
| http://cran.rstudio.com/web/packages/rYoutheria/index.html | https://cran.rstudio.com/web/packages/rYoutheria/index.html |
| http://cran.rstudio.com/web/packages/raincpc/index.html | https://cran.rstudio.com/web/packages/raincpc/index.html |
| http://cran.rstudio.com/web/packages/rainfreq/index.html | https://cran.rstudio.com/web/packages/rainfreq/index.html |
| http://cran.rstudio.com/web/packages/rbhl/index.html | https://cran.rstudio.com/web/packages/rbhl/index.html |
| http://cran.rstudio.com/web/packages/rbison/index.html | https://cran.rstudio.com/web/packages/rbison/index.html |
| http://cran.rstudio.com/web/packages/rbitcoinchartsapi/index.html | https://cran.rstudio.com/web/packages/rbitcoinchartsapi/index.html |
| http://cran.rstudio.com/web/packages/rcanvec/index.html | https://cran.rstudio.com/web/packages/rcanvec/index.html |
| http://cran.rstudio.com/web/packages/rdatamarket/index.html | https://cran.rstudio.com/web/packages/rdatamarket/index.html |
| http://cran.rstudio.com/web/packages/rdian/index.html | https://cran.rstudio.com/web/packages/rdian/index.html |
| http://cran.rstudio.com/web/packages/rebird/index.html | https://cran.rstudio.com/web/packages/rebird/index.html |
| http://cran.rstudio.com/web/packages/redcapAPI/index.html | https://cran.rstudio.com/web/packages/redcapAPI/index.html |
| http://cran.rstudio.com/web/packages/rentrez/index.html | https://cran.rstudio.com/web/packages/rentrez/index.html |
| http://cran.rstudio.com/web/packages/retrosheet/index.html | https://cran.rstudio.com/web/packages/retrosheet/index.html |
| http://cran.rstudio.com/web/packages/reutils/index.html | https://cran.rstudio.com/web/packages/reutils/index.html |
| http://cran.rstudio.com/web/packages/rfigshare/index.html | https://cran.rstudio.com/web/packages/rfigshare/index.html |
| http://cran.rstudio.com/web/packages/rfishbase/index.html | https://cran.rstudio.com/web/packages/rfishbase/index.html |
| http://cran.rstudio.com/web/packages/rfisheries/index.html | https://cran.rstudio.com/web/packages/rfisheries/index.html |
| http://cran.rstudio.com/web/packages/rgbif/index.html | https://cran.rstudio.com/web/packages/rgbif/index.html |
| http://cran.rstudio.com/web/packages/rnbn/index.html | https://cran.rstudio.com/web/packages/rnbn/index.html |
| http://cran.rstudio.com/web/packages/rnoaa/index.html | https://cran.rstudio.com/web/packages/rnoaa/index.html |
| http://cran.rstudio.com/web/packages/rnrfa/index.html | https://cran.rstudio.com/web/packages/rnrfa/index.html |
| http://cran.rstudio.com/web/packages/ropensecretsapi/index.html | https://cran.rstudio.com/web/packages/ropensecretsapi/index.html |
| http://cran.rstudio.com/web/packages/rplos/index.html | https://cran.rstudio.com/web/packages/rplos/index.html |
| http://cran.rstudio.com/web/packages/rpubchem/index.html | https://cran.rstudio.com/web/packages/rpubchem/index.html |
| http://cran.rstudio.com/web/packages/rredlist/index.html | https://cran.rstudio.com/web/packages/rredlist/index.html |
| http://cran.rstudio.com/web/packages/rscopus/index.html | https://cran.rstudio.com/web/packages/rscopus/index.html |
| http://cran.rstudio.com/web/packages/rsnps/index.html | https://cran.rstudio.com/web/packages/rsnps/index.html |
| http://cran.rstudio.com/web/packages/rsunlight/index.html | https://cran.rstudio.com/web/packages/rsunlight/index.html |
| http://cran.rstudio.com/web/packages/rtimes/index.html | https://cran.rstudio.com/web/packages/rtimes/index.html |
| http://cran.rstudio.com/web/packages/rusda/index.html | https://cran.rstudio.com/web/packages/rusda/index.html |
| http://cran.rstudio.com/web/packages/rvertnet/index.html | https://cran.rstudio.com/web/packages/rvertnet/index.html |
| http://cran.rstudio.com/web/packages/rwunderground/index.html | https://cran.rstudio.com/web/packages/rwunderground/index.html |
| http://cran.rstudio.com/web/packages/scholar/index.html | https://cran.rstudio.com/web/packages/scholar/index.html |
| http://cran.rstudio.com/web/packages/seeclickfixr/index.html | https://cran.rstudio.com/web/packages/seeclickfixr/index.html |
| http://cran.rstudio.com/web/packages/sejmRP/index.html | https://cran.rstudio.com/web/packages/sejmRP/index.html |
| http://cran.rstudio.com/web/packages/seqinr/index.html | https://cran.rstudio.com/web/packages/seqinr/index.html |
| http://cran.rstudio.com/web/packages/slackr/index.html | https://cran.rstudio.com/web/packages/slackr/index.html |
| http://cran.rstudio.com/web/packages/soilDB/index.html | https://cran.rstudio.com/web/packages/soilDB/index.html |
| http://cran.rstudio.com/web/packages/sorvi/index.html | https://cran.rstudio.com/web/packages/sorvi/index.html |
| http://cran.rstudio.com/web/packages/sos4R/index.html | https://cran.rstudio.com/web/packages/sos4R/index.html |
| http://cran.rstudio.com/web/packages/spocc/index.html | https://cran.rstudio.com/web/packages/spocc/index.html |
| http://cran.rstudio.com/web/packages/spoccutils/index.html | https://cran.rstudio.com/web/packages/spoccutils/index.html |
| http://cran.rstudio.com/web/packages/stationaRy/index.html | https://cran.rstudio.com/web/packages/stationaRy/index.html |
| http://cran.rstudio.com/web/packages/streamR/index.html | https://cran.rstudio.com/web/packages/streamR/index.html |
| http://cran.rstudio.com/web/packages/taxize/index.html | https://cran.rstudio.com/web/packages/taxize/index.html |
| http://cran.rstudio.com/web/packages/tm.plugin.webmining/index.html | https://cran.rstudio.com/web/packages/tm.plugin.webmining/index.html |
| http://cran.rstudio.com/web/packages/traits/index.html | https://cran.rstudio.com/web/packages/traits/index.html |
| http://cran.rstudio.com/web/packages/translate/index.html | https://cran.rstudio.com/web/packages/translate/index.html |
| http://cran.rstudio.com/web/packages/translateR/index.html | https://cran.rstudio.com/web/packages/translateR/index.html |
| http://cran.rstudio.com/web/packages/treebase/index.html | https://cran.rstudio.com/web/packages/treebase/index.html |
| http://cran.rstudio.com/web/packages/tseries/index.html | https://cran.rstudio.com/web/packages/tseries/index.html |
| http://cran.rstudio.com/web/packages/tumblR/index.html | https://cran.rstudio.com/web/packages/tumblR/index.html |
| http://cran.rstudio.com/web/packages/twitteR/index.html | https://cran.rstudio.com/web/packages/twitteR/index.html |
| http://cran.rstudio.com/web/packages/ukgasapi/index.html | https://cran.rstudio.com/web/packages/ukgasapi/index.html |
| http://cran.rstudio.com/web/packages/ustyc/index.html | https://cran.rstudio.com/web/packages/ustyc/index.html |
| http://cran.rstudio.com/web/packages/waterData/index.html | https://cran.rstudio.com/web/packages/waterData/index.html |
| http://cran.rstudio.com/web/packages/weatherData/index.html | https://cran.rstudio.com/web/packages/weatherData/index.html |
| http://cran.rstudio.com/web/packages/weatherr/index.html | https://cran.rstudio.com/web/packages/weatherr/index.html |
| http://cran.rstudio.com/web/packages/webchem/index.html | https://cran.rstudio.com/web/packages/webchem/index.html |
| http://cran.rstudio.com/web/packages/wordbankr/index.html | https://cran.rstudio.com/web/packages/wordbankr/index.html |
| http://cran.rstudio.com/web/packages/zendeskR/index.html | https://cran.rstudio.com/web/packages/zendeskR/index.html |
| http://ecoengine.berkeley.edu/ | https://ecoengine.berkeley.edu/ |
| http://factual.com/ | https://factual.com/ |
| http://figshare.com/ | https://figshare.com/ |
| http://github.com/expersso/ameco | https://github.com/expersso/ameco |
| http://github.com/mi2-warsaw/sejmRP/ | https://github.com/mi2-warsaw/sejmRP/ |
| http://github.com/ropensci/prism | https://github.com/ropensci/prism |
| http://openaddresses.io/ | https://openaddresses.io/ |
| http://www.idigbio.org/ | https://www.idigbio.org/ |
| http://www.quandl.com/ | https://www.quandl.com/ |
| http://www.thinknum.com/ | https://www.thinknum.com/ |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://api.stlouisfed.org/docs/fred/ | https://research.stlouisfed.org/docs/api/fred/ |
| http://ecodataretriever.org/ | http://www.ecodataretriever.org |
| http://here.com/ | https://maps.here.com/ |
| http://www.ceh.ac.uk/data/nrfa/ | http://nrfa.ceh.ac.uk |
| http://www.cryptsy.com | https://www.cryptsy.com/ |
| http://www.ggdc.net/maddison | http://www.ggdc.net/maddison/ |
| http://www.imgur.com | http://imgur.com/ |
| http://www.iplantcollaborative.org/discover/discovery-environment | http://www.iplantcollaborative.org/ci/discovery-environment |
| http://www.jsonstudio.com | http://jsonstudio.com/ |
| http://www.nbn.org.uk | http://nbn.org.uk/ |
| http://www.scribd.com | https://www.scribd.com/ |
| https://cloud.google.com/genomics | https://cloud.google.com/genomics/ |
| https://cran.r-project.org/src/contrib/Archive/GhcnDaily | https://cran.r-project.org/src/contrib/Archive/GhcnDaily/ |
| https://cran.r-project.org/src/contrib/Archive/gooJSON | https://cran.r-project.org/src/contrib/Archive/gooJSON/ |
| https://cran.r-project.org/src/contrib/Archive/ngramr | https://cran.r-project.org/src/contrib/Archive/ngramr/ |
| https://cran.r-project.org/src/contrib/Archive/rgauges | https://cran.r-project.org/src/contrib/Archive/rgauges/ |
| https://developer.here.com/geocoder | https://developer.here.com/plans/api/geocoder |
| https://www.github.com/expersso/WHO | https://github.com/expersso/WHO |

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
Oops .. did not see CONTRIBUTING.md

**Comment by ashander** [comment]
No worries, this seems helpful. We could re-open it and merge it, if you could
- [ ] change the corrected todo wiki link (one of the GitHub redirects) to  https://github.com/ropensci/webservices/wiki/ToDo  (I've edited your comment to change this but it needs to be changed in the code

**Comment by ReadmeCritic** [comment]
Hm so I should be sending my changes to opendata.md?

**Comment by ashander** [comment]
Er, yes, that's important and should've been on my check list! Thanks for picking up on it. 

The makefile setup is a bit fragile, and has some dependencies in R. If you just make the changes in opendata.md you needn't run all the steps in contributing.md

**Comment by ReadmeCritic** [comment]
Will try that

**Pull request closed without merging**
