### PR TITLE
Fixes for remainder of #4

### PR DESCRIPTION
**Pull request by ashander**
- adding markers for paid and account-required
- updating contrib guidelines
- removing less data oriented API wrappers

### CODE REVIEW

**Comment by ashander** [comment]
Fixes #4

**Comment by ashander** [comment]
Since they're small issues, I just added fixes for #26 and #28 to this PR

**Comment by leeper** [comment]
@ashander You should have write permission for this repo. Did you accept your invitation to join the "webservices team"?

**Comment by ashander** [comment]
Ok nice. 

But  I didn't see the invite. Weirdly, GitHub invites seem to be getting lost for me. (Another just did at least.) They don't show in my notifications or email. I'll try to find it

- Jaime

**Pull request merged**
