### PR TITLE
Added abettor package under Sports

### PR DESCRIPTION
**Pull request by phillc73**

### CODE REVIEW

**Comment by ashander** [comment]
Thanks! For some reason, though, this changes every line of `opendata.md`. I'm guessing this is a lineendings issue, which I'll look into further. What OS were you using to edit `opendata.md`?

We need to fix this for the repository in general as outlined here https://help.github.com/articles/dealing-with-line-endings/

**Comment by phillc73** [comment]
I edited the file with RStudio Version 0.99.484 on Debian Sid 64-bit.

Sorry about the line endings!

**Comment by ashander** [comment]
Thanks for the info. 

No worries, this is an issue we need to figure out in general for this repo 

- Jaime

**Comment by ashander** [comment]
Thanks for this change. I'm sorry about the line endings issue, which I think we've fixed. I went ahead and merged your addition as part of testing that fix.

Note that unfortunately this means your contribution won't be picked up by github, etc. Sorry about that but I hope it won't prevent you from submitting another PR.

**Pull request closed without merging**
